DELETE FROM SHARE_CLASS_SNAPSHOT;
DELETE FROM SHARE_CLASS;
DELETE FROM PORTFOLIO_SNAPSHOT;
DELETE FROM PORTFOLIO;
DELETE FROM TRADABLE_ENTITY;
DELETE FROM INTEREST_RATE_SCHEDULE;
DELETE FROM PUT_SCHEDULE;
DELETE FROM INSTRUMENT;
DELETE FROM CALENDAR_DATE;

INSERT INTO CALENDAR_DATE (CALENDAR_DT, CREATE_ID) VALUES (TO_DATE('2016-12-20', 'YYYY-MM-DD'), '123');
INSERT INTO CALENDAR_DATE (CALENDAR_DT,CREATE_ID) VALUES (TO_DATE('2017-01-08', 'YYYY-MM-DD'),'100');

INSERT INTO PORTFOLIO (PORTFOLIO_SID, PORTFOLIO_ID,PORTFOLIO_SHORT_NM, FDR_DISTRIBUTION_ELIGIBLE_IND, EFFECTIVE_DT, EXPIRATION_DT, HASH_KEY_TXT, CREATE_ID) 
VALUES (222, 555, 'portfolio1', 'Y', TO_DATE('2016-12-10', 'YYYY-MM-DD'), TO_DATE('2016-12-25', 'YYYY-MM-DD'), 'phash', '123');


INSERT INTO PORTFOLIO_SNAPSHOT (PORTFOLIO_SNAPSHOT_SID, PORTFOLIO_SID,REPORTING_DT,CREATE_ID) 
VALUES (666, 222, TO_DATE('2016-12-20', 'YYYY-MM-DD'),'123');

    
INSERT INTO SHARE_CLASS (SHARE_CLASS_SID, PORTFOLIO_SID, TRANSFER_AGENT_SHARE_CLASS_ID, EFFECTIVE_DT, EXPIRATION_DT, HASH_KEY_TXT, CREATE_ID) 
VALUES (111, 222, 333, TO_DATE('2016-12-10', 'YYYY-MM-DD'), TO_DATE('2016-12-25', 'YYYY-MM-DD'), 'shash', '123');

INSERT INTO SHARE_CLASS_SNAPSHOT (SHARE_CLASS_SNAPSHOT_SID, REPORTING_DT, SHARE_CLASS_SID,
    DER_MM_7_DAY_YIELD_PCT, DER_MM_7_DAY_N1A_YIELD_PCT, DER_MM_1_DAY_N1A_YIELD_PCT, DER_MM_RESTATE_1_DAY_YIELD_PCT, CREATE_ID) 
    VALUES (121, TO_DATE('2016-12-20', 'YYYY-MM-DD'), 111, 10, 20, 30, 40, '123');


INSERT INTO INSTRUMENT (INSTRUMENT_SID, INSTRUMENT_ID,EFFECTIVE_DT, EXPIRATION_DT, HASH_KEY_TXT,TAX_EXCL_LOC_CD, CREATE_ID) 
VALUES (777, 888,TO_DATE('2016-12-10', 'YYYY-MM-DD'),TO_DATE('2016-12-25', 'YYYY-MM-DD'),'ihash', 'tax', '123');

    
INSERT INTO PUT_SCHEDULE (PUT_SCHEDULE_SID, INSTRUMENT_SID, PUT_TERMS_SEQ_NBR, PUT_DT, EFFECTIVE_DT, EXPIRATION_DT, HASH_KEY_TXT,CREATE_ID) 
VALUES (999, 777, 789, TO_DATE('2016-12-20', 'YYYY-MM-DD'), TO_DATE('2016-12-10', 'YYYY-MM-DD'), TO_DATE('2016-12-25', 'YYYY-MM-DD'), 'ihash','123');
    
INSERT INTO INTEREST_RATE_SCHEDULE ( INTEREST_RATE_SCHEDULE_SID, INSTRUMENT_SID, INTEREST_RATE_TYPE_CD, INTEREST_RATE_EFF_DT, EFFECTIVE_DT, EXPIRATION_DT, HASH_KEY_TXT, CREATE_ID) 
VALUES (998, 777, 'cd',TO_DATE('2016-12-20', 'YYYY-MM-DD'),TO_DATE('2016-12-10', 'YYYY-MM-DD'),TO_DATE('2016-12-25', 'YYYY-MM-DD'),'ihash','123');
    
INSERT INTO TRADABLE_ENTITY ( TRADABLE_ENTITY_SID, INSTRUMENT_SID, TRADABLE_ENTITY_ID, EFFECTIVE_DT, EXPIRATION_DT, HASH_KEY_TXT, CREATE_ID) 
VALUES (997, 777, 789, TO_DATE('2016-12-20', 'YYYY-MM-DD'), TO_DATE('2016-12-10', 'YYYY-MM-DD'), 'ihash','123');
    

