/*
 * Copyright (c) 2017 TopCoder, Inc. All rights reserved.
 */
package com.csa.apex.fundyield.fayacommons.entities;

import java.util.Date;

/**
 * Versionable entity.
 * @author [es], TCSDEVELOPER
 * @version 1.0
 * @since FAYA Java App - Phase 1 Updates Code Challenge
 */
public abstract class Versionable extends Auditable {

    /**
     * A Date generated by data load process to indicate starting when the the record values are valid.
     */
	@ColumnName("EFFECTIVE_DT")
    private Date effectiveDate;

    /**
     * A Date generated by data load process to indicate starting when the the record values become in-valid. A future
     * default date will be generated where the record is still valid (e.g: 12/31/9999).
     */
	@ColumnName("EXPIRATION_DT")
    private Date expirationDate;

    /**
     * Helps in maintaining different versions of data when there is change in any attribute for same Table. This is
     * done by comparing hash key value for existing and new row. The hash key is generated using all attributes on a
     * given table. If they match then no new row is created. If not a new version is added. Version is added by
     * stamping end date of previous version and creating new row with start version time.
     */
	@ColumnName("HASH_KEY_TXT")
    private String hashKeyTxt;

    /**
     * Constructor.
     */
    protected Versionable() {
        // default empty constructor
    }

    /**
     * Getter method for property <tt>effectiveDate</tt>.
     * @return property value of effectiveDate
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Setter method for property <tt>effectiveDate</tt>.
     * @param effectiveDate value to be assigned to property effectiveDate
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * Getter method for property <tt>expirationDate</tt>.
     * @return property value of expirationDate
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * Setter method for property <tt>expirationDate</tt>.
     * @param expirationDate value to be assigned to property expirationDate
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * Getter method for property <tt>hashKeyTxt</tt>.
     * @return property value of hashKeyTxt
     */
    public String getHashKeyTxt() {
        return hashKeyTxt;
    }

    /**
     * Setter method for property <tt>hashKeyTxt</tt>.
     * @param hashKeyTxt value to be assigned to property hashKeyTxt
     */
    public void setHashKeyTxt(String hashKeyTxt) {
        this.hashKeyTxt = hashKeyTxt;
    }

}
