before_script:
  - which java
  - pwd
 
build-seccom:
  script:
      - mvn -f seccommons/pom.xml clean install

build-customerapi:
  script:
      - mvn install:install-file -Dfile=customerapi/lib/ojdbc6.jar -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0 -Dpackaging=jar
      - mvn -f customerapi/pom.xml clean install

build-secyield:
  script:
    - mvn -f secyieldapi/pom.xml clean install
