Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('TIPS','TIPS Income','INCOME','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('COUPON','Coupon Income','INCOME','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('STANDARD','Standard Income','INCOME','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('EQUITY','Equity Income','INCOME','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('PAYDOWN','Paydown Income','INCOME','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('YTM','YTM Yield','YIELD','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('COUP_RATE','Coupon Rate Yield','YIELD','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('CASH_FLOW','Cash Flow Yield','YIELD','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('DEFAULT','Default Yield','YIELD','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('DIVIDEND','Dividend Yield','YIELD','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('FOF','Fund of Fund Yield','YIELD','TESTER');
Insert into CALCULATION_ENGINE (CALCULATION_ENGINE_CD,CALCULATION_ENGINE_NM,CALCULATION_ENGINE_TYPE_CD,CREATE_ID) values ('DEF_INC','Default Income','INCOME','TESTER');

Insert into APPLICATION_USER (APPLICATION_USER_ID, CREATE_ID) values ('EXCEL_IMPORTOR', 'TESTER');
Insert into APPLICATION_USER (APPLICATION_USER_ID, CREATE_ID) values ('CALCULATOR', 'TESTER');

Insert into CALENDAR_DATE (CALENDAR_DT, CREATE_ID) values (TO_DATE('01/12/2014 00:00:00', 'dd/mm/yyyy hh24:mi:ss'), 'TESTER');
Insert into CALENDAR_DATE (CALENDAR_DT, CREATE_ID) values (TO_DATE(TO_CHAR(CURRENT_DATE, 'dd/mm/yyyy') || ' 00:00:00', 'dd/mm/yyyy hh24:mi:ss'), 'TESTER');
Insert into CALENDAR_DATE (CALENDAR_DT, CREATE_ID) values (TO_DATE(TO_CHAR(CURRENT_DATE + 1, 'dd/mm/yyyy') || ' 00:00:00', 'dd/mm/yyyy hh24:mi:ss'), 'TESTER');
COMMIT;