-- -----------------------
--  User secyield
-- -----------------------
CREATE USER secyield IDENTIFIED BY password DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, CREATE TABLE, CREATE TYPE, CREATE PROCEDURE, CREATE SEQUENCE TO secyield;
ALTER USER secyield QUOTA UNLIMITED ON USERS;

-- ------------------------
--  User test_secyield
-- ------------------------
CREATE USER test_secyield IDENTIFIED BY password DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, CREATE TABLE, CREATE TYPE, CREATE PROCEDURE, CREATE SEQUENCE TO test_secyield;
ALTER USER test_secyield QUOTA UNLIMITED ON USERS;
